project:
  type: book
  output-dir: docs

book:
  title: "Nusses kogebog"
  author: "Christian Knudse"
  date: "`r Sys.Date()`"
  chapters:
    - index.qmd
    - rmds/gris.qmd
    - rmds/kylling.qmd
    - rmds/ko.qmd
    - rmds/lam.qmd
    - rmds/vildt.qmd
    - rmds/pasta.qmd
    - rmds/green.qmd
    - rmds/sovsene.qmd
    - rmds/kondimenterne.qmd
    - rmds/specialiteterne.qmd
    - rmds/rester.qmd
    - rmds/hapserne.qmd
    - rmds/supperne.qmd
    - rmds/desserterne.qmd
    - rmds/bagning.qmd
    - rmds/marmeladerne.qmd
    - rmds/diverse.qmd
    - rmds/teori.qmd
    - rmds/omregninger.qmd
    - rmds/menuerne.qmd
    - rmds/bagning.qmd
    - rmds/drinks.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo



